# Generated by Django 3.0.6 on 2020-06-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryThroughEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=10, null=True, verbose_name='Fecha desde')),
                ('date_to', models.CharField(max_length=10, null=True, verbose_name='Fecha hasta')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Category', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Tarea / Cargo',
                'verbose_name_plural': 'Tareas / Cargos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationThroughEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=10, null=True, verbose_name='Fecha desde')),
                ('date_to', models.CharField(max_length=10, null=True, verbose_name='Fecha hasta')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Destination', verbose_name='Destino')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp', models.CharField(max_length=4, verbose_name='Legajo Personal')),
                ('cuil', models.CharField(max_length=11, verbose_name='CUIL')),
                ('ndoc', models.CharField(max_length=10, verbose_name='Documento')),
                ('tdoc', models.CharField(choices=[('1', 'DNI'), ('2', 'LC'), ('3', 'LE')], default='1', max_length=1, verbose_name='Tipo Documento')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('piso', models.CharField(max_length=3, verbose_name='Piso')),
                ('unidad', models.CharField(max_length=1, verbose_name='Unidad')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(max_length=15, null=True, verbose_name='Celular')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Email')),
                ('foto', models.CharField(max_length=5, null=True, verbose_name='Foto')),
                ('cpost', models.CharField(max_length=5, null=True, verbose_name='Código postal')),
                ('numero', models.CharField(max_length=5, null=True, verbose_name='Número')),
                ('observaciones', models.TextField(null=True, verbose_name='Observaciones')),
                ('horario', models.CharField(max_length=255, null=True, verbose_name='Horario')),
                ('horas_diarias', models.IntegerField(null=True, verbose_name='Horas diarias')),
                ('horas_semanales', models.IntegerField(null=True, verbose_name='Horas semanales')),
                ('horas_mensuales', models.IntegerField(null=True, verbose_name='Horas mensuales')),
                ('fechadealta', models.CharField(max_length=10, null=True, verbose_name='Fecha de alta')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['lp'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Marital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados civiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SectorThroughEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=10, null=True, verbose_name='Fecha desde')),
                ('date_to', models.CharField(max_length=10, null=True, verbose_name='Fecha hasta')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Employee', verbose_name='Empleado')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Sector', verbose_name='Sector')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='barrio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abm.Neighborhood', verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ManyToManyField(through='abm.CategoryThroughEmployee', to='abm.Category'),
        ),
        migrations.AddField(
            model_name='employee',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abm.Agreement', verbose_name='Convenio'),
        ),
        migrations.AddField(
            model_name='employee',
            name='destination',
            field=models.ManyToManyField(through='abm.DestinationThroughEmployee', to='abm.Destination'),
        ),
        migrations.AddField(
            model_name='employee',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abm.Status', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='employee',
            name='estado_civil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abm.Marital', verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='employee',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abm.Location', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='employee',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abm.Province', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sector',
            field=models.ManyToManyField(through='abm.SectorThroughEmployee', to='abm.Sector'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abm.Sex', verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='destinationthroughemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='categorythroughemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Employee', verbose_name='Empleado'),
        ),
    ]
