# Generated by Django 3.0.6 on 2020-06-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fecha_nacimiento',
            field=models.CharField(max_length=10, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.CreateModel(
            name='ChargeThroughEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=10, null=True, verbose_name='Fecha desde')),
                ('date_to', models.CharField(max_length=10, null=True, verbose_name='Fecha hasta')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Charge', verbose_name='Cargo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Employee', verbose_name='Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='charge',
            field=models.ManyToManyField(through='abm.ChargeThroughEmployee', to='abm.Charge'),
        ),
    ]
