# Generated by Django 3.0.6 on 2020-06-10 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0002_auto_20200609_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='convenio',
        ),
        migrations.AddField(
            model_name='employee',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abm.Agreement', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fechadealta',
            field=models.DateField(null=True, verbose_name='Fecha de alta'),
        ),
    ]
