# Generated by Django 3.0.6 on 2020-06-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0003_auto_20200609_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='amtedyc',
            field=models.IntegerField(null=True, verbose_name='AMTEDyC'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cspfa',
            field=models.IntegerField(null=True, verbose_name='CSPFA'),
        ),
        migrations.AddField(
            model_name='employee',
            name='deportes',
            field=models.CharField(max_length=255, null=True, verbose_name='Deportes'),
        ),
        migrations.AddField(
            model_name='employee',
            name='obra_social',
            field=models.CharField(max_length=255, null=True, verbose_name='Obra social'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sindicato',
            field=models.IntegerField(null=True, verbose_name='Sindicato'),
        ),
        migrations.AddField(
            model_name='employee',
            name='temporada',
            field=models.IntegerField(null=True, verbose_name='Temporada'),
        ),
    ]
