# Generated by Django 3.0.6 on 2020-06-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0004_auto_20200610_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fechadealta',
        ),
    ]
