# Generated by Django 3.0.6 on 2020-06-10 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0005_remove_employee_fechadealta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['name'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AddField(
            model_name='employee',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abm.Agreement', verbose_name='Convenio'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abm.Contract', verbose_name='Contrato'),
        ),
    ]
