# Generated by Django 3.0.6 on 2020-06-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0006_auto_20200610_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['name'], 'verbose_name': 'Convenio', 'verbose_name_plural': 'Convenios'},
        ),
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.CharField(max_length=10, verbose_name='Fecha')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Alta',
                'verbose_name_plural': 'Altas',
                'ordering': ['up'],
            },
        ),
    ]
