# Generated by Django 3.0.6 on 2020-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0007_auto_20200612_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ups',
            name='up',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
