# Generated by Django 3.0.6 on 2020-06-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0008_auto_20200612_0558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ups',
            options={'ordering': ['date'], 'verbose_name': 'Alta', 'verbose_name_plural': 'Altas'},
        ),
        migrations.RenameField(
            model_name='ups',
            old_name='up',
            new_name='date',
        ),
        migrations.CreateModel(
            name='Downs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Baja',
                'verbose_name_plural': 'Bajas',
                'ordering': ['date'],
            },
        ),
    ]
