# Generated by Django 3.0.6 on 2020-06-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0009_auto_20200612_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Down',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('number', models.CharField(max_length=4, verbose_name='Número')),
                ('year', models.CharField(max_length=4, verbose_name='Año')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Document', verbose_name='Documento')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Baja',
                'verbose_name_plural': 'Bajas',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DownReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='Ups',
            new_name='Up',
        ),
        migrations.DeleteModel(
            name='Downs',
        ),
        migrations.AddField(
            model_name='down',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.DownReason', verbose_name='Motivo'),
        ),
    ]
