# Generated by Django 3.0.6 on 2020-06-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0010_auto_20200612_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Formacion',
                'verbose_name_plural': 'Formaciones',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='downreason',
            options={'ordering': ['name'], 'verbose_name': 'Motivo baja', 'verbose_name_plural': 'Motivos baja'},
        ),
    ]
