# Generated by Django 3.0.6 on 2020-06-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0011_auto_20200612_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingThroughEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, null=True, verbose_name='Fecha')),
                ('complete', models.CharField(max_length=2, null=True, verbose_name='Completo')),
                ('institute', models.CharField(max_length=200, null=True, verbose_name='Institución')),
                ('grade', models.CharField(max_length=200, null=True, verbose_name='Título')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Employee', verbose_name='Empleado')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abm.Training', verbose_name='Formación')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='training',
            field=models.ManyToManyField(through='abm.TrainingThroughEmployee', to='abm.Training'),
        ),
    ]
