# Generated by Django 3.0.6 on 2020-06-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0012_auto_20200612_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='amtedyc',
            field=models.IntegerField(choices=[('0', 'No'), ('1', 'Si')], default='0', null=True, verbose_name='AMTEDyC'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cspfa',
            field=models.IntegerField(choices=[('0', 'No'), ('1', 'Si')], default='0', null=True, verbose_name='CSPFA'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deportes',
            field=models.IntegerField(choices=[('0', 'No'), ('1', 'Si')], default='0', null=True, verbose_name='Deportes'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sindicato',
            field=models.IntegerField(choices=[('0', 'No'), ('1', 'Si')], default='0', null=True, verbose_name='Sindicato'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='temporada',
            field=models.IntegerField(choices=[('0', 'No'), ('1', 'Si')], default='0', null=True, verbose_name='Temporada'),
        ),
    ]
