# Generated by Django 3.0.6 on 2020-06-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0014_auto_20200612_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='estado',
        ),
        migrations.AlterField(
            model_name='employee',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='piso',
            field=models.IntegerField(verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tdoc',
            field=models.CharField(choices=[('1', 'DNI'), ('2', 'LC'), ('3', 'LE')], default='1', max_length=1, verbose_name='Tipo'),
        ),
    ]
