# Generated by Django 3.0.6 on 2020-06-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0015_auto_20200612_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fecha_nacimiento',
            field=models.CharField(max_length=10, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
